// This file is generated by github.com/komarovn654/embedded_configurator. Do not change it.
// PLL header:
// required frequency - 168000000 Hz
// pll source - HSE

#pragma once

#define HSE_FREQUENCY (8000000)
#define HSI_FREQUENCY (16000000)
#define PLL_SOURCE    PLL_SOURCE_HSE

#define PLL_REQUIRED_FREQUENCY (168000000)
#define PLL_SOURCE_FREQUENCY   (8000000)
#define PLL_48CLK_FREQUENCY    (48000000)

#define PLL_DIV_FACTOR_M (4)
#define PLL_DIV_FACTOR_N (168)
#define PLL_DIV_FACTOR_P (0)
#define PLL_DIV_FACTOR_Q (7)
