#pragma once

#define PLL_SOURCE_HSE (1)
#define PLL_SOURCE_HSI (0)

#define RCC_PLLCFGR_RESET_STATE (0x24003010)
#define RCC_PLLCFGR_PLLM_POS    (0x00)
#define RCC_PLLCFGR_PLLM_MSK    (0x3F << RCC_PLLCFGR_PLLM_POS)
#define RCC_PLLCFGR_PLLN_POS    (0x06)
#define RCC_PLLCFGR_PLLN_MSK    (0x3FF << RCC_PLLCFGR_PLLN_POS)
#define RCC_PLLCFGR_PLLP_POS    (0x10)
#define RCC_PLLCFGR_PLLP_MSK    (0x03 << RCC_PLLCFGR_PLLP_POS)
#define RCC_PLLCFGR_PLLSRC_POS  (0x16)
#define RCC_PLLCFGR_PLLSRC_MSK  (0x01 << RCC_PLLCFGR_PLLSRC_POS)
#define RCC_PLLCFGR_PLLQ_POS    (0x18)
#define RCC_PLLCFGR_PLLQ_MSK    (0x0F << RCC_PLLCFGR_PLLQ_POS)
